### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by huard** [pangeo-data/xESMF#137]
I suggest we make a 0.7.0 release soon, including notes suggesting to avoid 0.6.1.

**Comment by huard** [comment]
My question is whether this should be a labeled 0.6.2 or 0.7.0 ?
@raphaeldussin @aulemahal

**Comment by raphaeldussin** [comment]
`0.6.2` since we haven't introduce a new feature

**Comment by aulemahal** [comment]
I agree with 0.6.2. The last PR changes things internally, but there's no real new feature associated with these changes. At least, none more than in 0.6.1.

**Comment by huard** [comment]
Ok, opened PR, please review. Will merge tomorrow and issue the new release.
