### ISSUE TITLE
'lat' 'lon' not accepted as regrid target dimension names with method="conservative"

### ISSUE THREAD

**Issue by mangecoeur** [pangeo-data/xESMF#146]
Modifying the code from the [documentation](https://pangeo-xesmf.readthedocs.io/en/latest/notebooks/Rectilinear_grid.html#Prepare-data) to use method 'conservative' fails with `KeyError` (the snippet works fine for me with method='bilinear')

This fails with keyerror:

```python
ds = xr.tutorial.open_dataset(
    "air_temperature"
)  # use xr.tutorial.load_dataset() for xarray<v0.11.0

ds_out = xr.Dataset(
    {
        "lat": (["lat"], np.arange(16, 75, 1.0)),
        "lon": (["lon"], np.arange(200, 330, 1.5)),
    }
)

regridder = xe.Regridder(ds, ds_out, method="conservative")
regridder  
```

Renaming the target dataset dimensions to latitude, longitude makes it work.

```python
ds = xr.tutorial.open_dataset(
    "air_temperature"
)  # use xr.tutorial.load_dataset() for xarray<v0.11.0

ds_out = xr.Dataset(
    {
        "latitude": (["latitude"], np.arange(16, 75, 1.0)),
        "longitude": (["longitude"], np.arange(200, 330, 1.5)),
    }
)

regridder = xe.Regridder(ds, ds_out, method="conservative")
regridder  # print basic regridder information.
```

Versions: xESMF 0.6.2, Python 3.9 (conda-forge), Ubuntu 20.04, working in JupyerLab notebook

**Comment by raphaeldussin** [comment]
Hi @mangecoeur 

Conservative remapping needs the corner coordinates to properly compute the area of the cells. xesmf first look for variables `lon_b` and `lat_b` (bounds) in the dataset for this. Recent implementation of cf_xarray allows to lift this requirement (cf_xarray will build this for you). This is what it does for the input dataset. However, when you create the output dataset using lon/lat, it does not create a proper cf xarray dataset. @aulemahal do you have time to look into bulletproofing this?

**Comment by huard** [comment]
cf-xarray uses heuristics based on the CF convention to identify lats and lons: https://cf-xarray.readthedocs.io/en/latest/coord_axes.html#coordinate-names

I suggest we stick to those and not try to make guesses beyond those heuristics.

**Comment by raphaeldussin** [comment]
I agree with you @huard but there may be a way to catch the error and return a more informative message?

**Comment by aulemahal** [comment]
We could indeed catch any "KeyError" and tell the user that sometime might be wrong with the coordinate names/attrs. 
I note that cf_xarray has a `guess_coord_axis` function that would have understood `lat` and `lon` as latitude and longitude. As this uses regex patterns and is a bit more arbitrary than the normal coord detection, it is not executed automatically. But we could refer to it in the docs and in the error message, as it would have solved the issue here.
