### ISSUE TITLE
More options for `grid_global`

### ISSUE THREAD

**Issue by jbusecke** [pangeo-data/xESMF#149]
I find myself using the utility function `xe.util.grid_global()` quite a bit, but was wondering if it would be possible to enable to change the default longitude convention (-180, 180) to e.g. (0,360). Its a minor thing, but this would help me with my current, very Pacific focused work. 

Maybe this is already possible? If not, id be happy to submit a PR.

On a bit longer tangent: This functionality has quite a bit of overlap with [xgcm.autogenerate](https://xgcm.readthedocs.io/en/latest/api.html#module-xgcm.autogenerate), which is old, clunky, and will probably be dropped in the next xgcm release. I would love to get peoples opinion here if we could combine the ability to create completely new lon/lat datasets with bounds (xesmf) with the ability to generate bounds for gridded datasets which only provide cell center coordinates (xgcm.autogenerate).

**Comment by raphaeldussin** [comment]
I'm not too familiar with this function but I'll be happy to review a PR extending its capabilities

**Comment by jbusecke** [comment]
Thanks Raph. Ill get to it sometime soon. Might have to wait until after Ocean Sciences.

**Comment by jbusecke** [comment]
Could you assign me, just so I dont forget?
