### ISSUE TITLE
ESMF extrapolation

### ISSUE THREAD

**Issue by raphaeldussin** [pangeo-data/xESMF#15]
ESMF v8+ have now an extrapolation scheme too.
I volunteer myself to look into it unless someone else has time to do it.

**Comment by trondkr** [comment]
@raphaeldussin I have created a Jupyter notebook for testing extrapolation features of ESMF 8.0.1 with xesmf using the pull request JiaweiZhuang/xESMF#97 from @RondeauG. The test case can be downloaded from my Dropbox [here ](https://www.dropbox.com/sh/ftobbskdui7tcoe/AAAQwL5sq2JmjLsTuO4rxOmua?dl=0) and contains two small netcdf files for source and destination grids. The test interpolates oxygen data in 4D from 1/4 resolution to 1/12th degrees resolution for the California coast. If you think it can be helpful feel free to use it. Cheers, Trond

**Comment by raphaeldussin** [comment]
@trondkr thanks a lot, this is very helpful!

**Comment by raphaeldussin** [comment]
fixed by #20
