### ISSUE TITLE
Regrid discrepancy between xESMF and CDO 

### ISSUE THREAD

**Issue by mtrimp2** [pangeo-data/xESMF#151]
I am noticing a discrepancy between datasets regridded by xESMF and CDO with the same parameters. When regridding a global dataset, for example, most of the values are identical, with the exception of a few choice points on the globe (plot attached- note that I selected "center plot on zero", which is why the plot appears to have a scale from 0.0 - 0.0). The differences exist when regridded with both bilinear and nearest neighbor interpolations, and the problem occurs for many different variables. I have attached a zip file with two sample output nc4 files from both CDO and xESMF, regridded with the same parameters. I am not sure if these different values are due to a difference in the ways that xe/cdo handle nan values, or something similar? I was just wondering if anyone could shed some light on this. Thank you!
[regrid_outputs.zip](https://github.com/pangeo-data/xESMF/files/8061429/regrid_outputs.zip)
<img width="1061" alt="Screen Shot 2022-02-14 at 9 16 59 AM" src="https://user-images.githubusercontent.com/60446090/153881457-6a2b3c4a-c8c8-4c58-a70d-da51d0c23d43.png">

**Comment by raphaeldussin** [comment]
did this answer your question?

**Comment by mtrimp2** [comment]
yes, thank you!
