### ISSUE TITLE
12+ hour downscaling?

### ISSUE THREAD

**Issue by jwynnsmith** [pangeo-data/xESMF#152]
Hello all
Should I expect an xESMF python downscaling of a 5424 x 5424 grid to a 128x162 grid to take 12+ hours to run?  Am I not missing something or do I have something here that would slow down the run?  
Here is the script below:

import numpy as np
import xesmf as xe
from netCDF4 import Dataset

data = np.genfromtxt('./glm_flash_freq_052019.csv', delimiter=',')
data = np.ma.masked_where(data <0.00000000000000000000001, data)
print(data)

lon, lat = np.meshgrid(np.linspace(0.5, 5424.5, 5424), np.linspace(0.5, 5424.5, 5424))
lon_b, lat_b = np.meshgrid(np.linspace(0, 5424, 5425), np.linspace(0, 5424, 5425))
grid_in = {"lon": lon, "lat": lat, "lon_b": lon_b, "lat_b": lat_b}

####-------- Obtain range of longitude and latitude of the out file (downscaled grid)

lon_out_b = np.linspace(-155, 5, 129)
lon_out = np.linspace(-154.375, 4.375, 128)
lat_out_b = np.linspace(-81, 81, 163)
lat_out = np.linspace(-80.5, 80.5, 162)
grid_out = {"lon": lon_out, "lat": lat_out, "lon_b": lon_out_b, "lat_b": lat_out_b}

####---------- Apply xESMF Regridder

regridder = xe.Regridder(grid_in, grid_out, "conservative")
print(regridder)
data_out = regridder(data)  # regrid a basic numpy array
____________________________

Thanks
Jonathan

**Comment by raphaeldussin** [comment]
Hi @jwynnsmith 

I've run into similar problems when attempting large remapping such as yours. Unfortunately, at the moment xESMF can only call the ESMF Regrid algo in serial mode. I would like to see xESMF support the parallel weight generation using the MPI-enabled ESMF library but it's a big project and we don't have the bandwidth for this at the moment but contributions are welcome!

Fortunately there is a workaround! You can use ESMF command line tools to create the weights or the output field. I wrote a page on the documentation here: https://xesmf.readthedocs.io/en/latest/large_problems_on_HPC.html

**Comment by jwynnsmith** [comment]
Hi @raphaeldussin 
In the example command below from: https://xesmf.readthedocs.io/en/latest/large_problems_on_HPC.html

mpirun -np 720 ESMF_Regrid -s source.nc -d output.nc -m bilinear --src_var elevation --dst_var elevation --netcdf4

Is the source.nc file a netcdf file with our high resolution grid data and is the output.nc a netcdf file with the coordinates of our downscaled grid?
Thanks
Jonathan

**Comment by raphaeldussin** [comment]
that is correct! ESMF_Regrid will read your "destination" grid file (output.nc) and then overwrite it with the remapped data and keeping the lon/lat of the destination grid.

**Comment by jwynnsmith** [comment]
@raphaeldussin and all
I implemented an ESMF_Regrid (see command below) and I where I have the high resolution satellite grid in the source.nc and the destination.nc file with an empty (all zeros) downscaled grid.  All of the settings are as suggested on the page you linked above. But I am left with the zero arrays in the destination.nc file after the run.  My high resolution data is on the order of e-13 to e-8.  Any suggestions?

mpirun -np 8 ESMF_Regrid -s source.nc -d destination.nc -m conserve --src_regional --src_var glm_ff --dst_var glm_ff --netcdf4

Here are the settings for the source and destination files which include bounds:

dimensions:
	lat = 5424 ;
	lon = 5424 ;
	bnds = 2 ;
variables:
	double glm_ff(lat, lon) ;
		glm_ff:_FillValue = NaN ;
		glm_ff:coordinates = "lon lat" ;
	int64 bnds(bnds) ;
	double lat(lat) ;
		lat:_FillValue = 1.e+20 ;
		lat:bounds = "lat_bnds" ;
		lat:long_name = "latitude" ;
		lat:units = "degrees_N" ;
	double lon(lon) ;
		lon:_FillValue = 1.e+20 ;
		lon:bounds = "lon_bnds" ;
		lon:long_name = "longitude" ;
		lon:units = "degrees_E" ;
	double lat_bnds(lat, bnds) ;
		lat_bnds:_FillValue = 1.e+20 ;
		lat_bnds:long_name = "latitude corner" ;
	double lon_bnds(lon, bnds) ;
		lon_bnds:_FillValue = 1.e+20 ;
		lon_bnds:long_name = "longitude corner" ;

// global attributes:
		:_NCProperties = "version=2,netcdf=4.7.4,hdf5=1.12.0," ;

----------------------------

netcdf destination {
dimensions:
	lat = 162 ;
	lon = 128 ;
	bnds = 2 ;
variables:
	double glm_ff(lat, lon) ;
		glm_ff:_FillValue = NaN ;
		glm_ff:coordinates = "lon lat" ;
	int64 bnds(bnds) ;
	double lat(lat) ;
		lat:_FillValue = 1.e+20 ;
		lat:bounds = "lat_bnds" ;
		lat:long_name = "latitude" ;
		lat:units = "degrees_N" ;
	double lon(lon) ;
		lon:_FillValue = 1.e+20 ;
		lon:bounds = "lon_bnds" ;
		lon:long_name = "longitude" ;
		lon:units = "degrees_E" ;
	double lat_bnds(lat, bnds) ;
		lat_bnds:_FillValue = 1.e+20 ;
		lat_bnds:long_name = "latitude corner" ;
	double lon_bnds(lon, bnds) ;
		lon_bnds:_FillValue = 1.e+20 ;
		lon_bnds:long_name = "longitude corner" ;

// global attributes:
		:_NCProperties = "version=2,netcdf=4.7.4,hdf5=1.12.0," ;

**Comment by raphaeldussin** [comment]
I had cases where this happen, you may want to transfer the issue to https://github.com/esmf-org/esmf
maybe @rokuingh or others can help you with this?

**Comment by jwynnsmith** [comment]
@raphaeldussin Thank you!
