### ISSUE TITLE
Inconsistent NaN value placements

### ISSUE THREAD

**Issue by trimpinm** [pangeo-data/xESMF#154]
Once again I am having an issue with certain data points coming up as NaN when regridding with xESMF, and numerical values when regridded with cdo.

I have attatched data comparisons for the CLDTMP variable from each dataset.

As shown in the images, upon performing bilinear regridding, it seems that all of the values are identical save for a few choice data points (for example 0.0 longitude, 42 latitude and 0.0 longitude, 54 latitude). In these points they appear as NaN on one dataset and not the other. I have attatched the original netcdf dataset, as well as the two sample netCDF files via zip file: [regrid_NaN_issue.zip](https://github.com/pangeo-data/xESMF/files/8171068/regrid_NaN_issue.zip)

Any help/insight is appreciated :)

**Comment by raphaeldussin** [comment]
I can see a couple of issues here:

1. did you provide a `mask` variable in your input dataset? without it specified explicitly, ESMF will treat NaNs the same way than regular values. I'll refer you to the documentation on this here:

https://xesmf.readthedocs.io/en/latest/notebooks/Masking.html

2. when you're remapping to a lower resolution, it could be preferable to use the `conservative_normed` method to really get the average value over a larger cell. Again the documentation will help you with this.

finally, cdo and ESMF are two different implementation of similar algorithms but there is no reason for them to produce bitwise identical solutions. It's up to the user to decide which solution is preferred.
