### ISSUE TITLE
Dependency refinement sparse, numba

### ISSUE THREAD

**Issue by zklaus** [pangeo-data/xESMF#158]
Currently, xESMF simply depends on `sparse`, with no lower bound, and does not depend on `numba` explicitly.
In conda-forge/esmvaltool-suite-feedstock#5 we ran into a problem where that leads to `numba` missing because older `sparse` builds do not depend on it.

I suggest that xESMF depends on `numba` itself since it is used in `smm.py` and thus a direct dependency.
I also wonder if you want to place a lower bound on the `sparse` dependency?

**Comment by raphaeldussin** [comment]
@zklaus that sounds like a good solution, what lower bound for `sparse` are you thinking of?

**Comment by zklaus** [comment]
@raphaeldussin, I don't know about the lower bound on `sparse`. My thinking was that a lower bound on sparse might pull in numba automatically, but also, I know that sparse has undergone substantial development and I am not sure which version is the oldest that you have done your tests with.

If you add the numba dependency (as I think you should because you are using it directly), there is no technical need for a lower bound on sparse. But if you know or suspect that you need a certain maturity from sparse, you may still consider it.
