### ISSUE TITLE
`numba` isn't included in `v0.6.2` conda-forge feedstock recipe

### ISSUE THREAD

**Issue by tomvothecoder** [pangeo-data/xESMF#170]
`numba` is introduced as a new dependency in `v0.6.2`. 

The `setup.py` file includes `numba`, so the PyPI release works fine:
https://github.com/pangeo-data/xESMF/blob/860311345212c3e5f52d08335eb758cf903d6787/setup.py#L23-L31

However, the conda-forge feedstock recipe does not include `numba`:
https://github.com/conda-forge/xesmf-feedstock/blob/fe72c86a62ed48b698eeb8e58acc50817bd954fc/recipe/meta.yaml#L16-L28

This results in environments and other packages that use `xesmf` to break with the following error:
```
File ~/miniconda3/envs/xcdat_test_dev/lib/python3.10/site-packages/xesmf/smm.py:7, in <module>
      4 import warnings
      5 from pathlib import Path
----> 7 import numba as nb
      8 import numpy as np
      9 import sparse as sps

ModuleNotFoundError: No module named 'numba'
```

This user has to manually install `numba` into their environment and packages that include `xesmf` must also include `numba` as a dependency (it should be installed implicitly via `xesmf`).

**Comment by aulemahal** [comment]
Sorry about that. Numba  is direct dependency of recent versions of sparse, which is an explicit dependency of xESMF 0.6.2. However, I didn't know that older versions of sparse did not use numba. This issue was solved with #168, but we have not released a new xESMF since.

**Comment by tomvothecoder** [comment]
No problem @aulemahal, I just wanted to make sure this was noted! I appreciate the quick update.

**Comment by jbusecke** [comment]
I am running into the same issue over at https://github.com/jbusecke/cmip6_preprocessing/runs/7102175665?check_suite_focus=true. Any chance for a bugfix release + conda-forge bump? Or is anything blocking that. Happy to help.

**Comment by raphaeldussin** [comment]
@aulemahal go for it!

**Comment by huard** [comment]
0.6.3 now available on conda.
