### ISSUE TITLE
Generate boundary automatically based on centers

### ISSUE THREAD

**Issue by zxdawn** [pangeo-data/xESMF#180]
Usually the satellite data only have the pixel center data, it would be nice to generate the boundary automatically. Here's one [example](https://gist.github.com/zxdawn/49c73e4d1ef9043580644e57eaa16d83) using xgcm to create the boundary arrays.

BTW, we want to [support xESMF conservative regridder in pyresample](https://github.com/pytroll/pyresample/issues/440#issuecomment-1175191749). The auto boundary could make it easier.

**Comment by aulemahal** [comment]
If you data is using a regular `lat` and `lon`  grid (both coordinates being 1D), then [`cf-xarray` has a function for that](https://cf-xarray.readthedocs.io/en/latest/generated/xarray.Dataset.cf.add_bounds.html?highlight=add_bounds#xarray.Dataset.cf.add_bounds)! Moreover, this function is already used by `xESMF` when bounds are missing.

There is an issue there for extending the function to 2D coordinates : xarray-contrig/cf-xarray#71.
Maybe the code from xgcm could be adapted and transposed there?

**Comment by zxdawn** [comment]
Thanks. I have mentioned the xgcm to cf-xarray issue. Should I keep this open until it's supported?

**Comment by huard** [comment]
I suggest to close this and open a new issue once there is functionality ready in cf-xarray that can be integrated here.
