### ISSUE TITLE
PyPI distribution name

### ISSUE THREAD

**Issue by zklaus** [pangeo-data/xESMF#183]
In using xesmf, we run into a problem because the distribution name on PyPI now is `pangeo-xesmf`, but the distribution name on the Github releases as well as the conda-forge releases is xesmf. That means that there is no consistent way to specify the xesmf dependency in both `setup.py` for pip installability and conda-forge's `meta.yml` for conda-forge installs.

I understand that there is a problem due to the ownership of the project on PyPI, but do you see a way forward to homogenize this again?

By and large, there are two possible solutions: Commit to the new `pangeo-xesmf` name and use it also for the Github releases and on conda-forge, or gain ownership of the xesmf project on PyPI, which, failing availability of the project owners usually can be achieved by contacting the PyPI admins.

In both cases, the conda-forge packages could be built from the Pypi distributions again.

**Comment by huard** [comment]
We now have ownership of PyPI xesmf. We just need to push xesmf to PyPI, but I'm running into problems with the SCM version. @ocefpaf do you have some time to look into how to push 0.7 to PyPI ?

**Comment by zklaus** [comment]
This is great :tada: Gave us a real headache for quite some time.

**Comment by huard** [comment]
xesmf 0.7.1 is now on PyPI. 

@ocefpaf I don't think the procedure to push to conda works now however. https://xesmf.readthedocs.io/en/latest/releases.html

**Comment by zklaus** [comment]
In conda-forge/xesmf-feedstock#30 I propose to go back to the PyPI releases as a source for Conda-forge (which is generally preferred). If adopted, that would mean that the procedure should work, though some steps become superfluous.

**Comment by ocefpaf** [comment]
> If adopted, that would mean that the procedure should work, though some steps become superfluous.

Yep. Here is my suggestion for a workflow but take that with a grain of salt b/c what works for someone may not work for others.

1. Retire the `CHANGES.rst` file b/c that is prone to errors and/or go stale;
2. Rely on GH UI to mint the release and populated the release notes/changelog;
3. Steps 2-4, 6 remain the same but no other action is required after that. The workflow should update the PyPI package automatic and then the conda-forge bot should pick it up.

**Comment by huard** [comment]
Opened a new issue to update the docs.
