### ISSUE TITLE
INSTALLATION ERROR

### ISSUE THREAD

**Issue by KashyapAnurag** [pangeo-data/xESMF#188]
I am trying to install xESMF using code "conda install -c conda-forge xesmf" it is showing following error:

![image](https://user-images.githubusercontent.com/91251342/185389921-a30e1625-d3fa-4096-8a75-c5b2fe309bfe.png)

I have tried installing it in new environment too, but didn't worked. Please help me installing it.

**Comment by aulemahal** [comment]
Hi @KashyapAnurag , I'm not sure I see an error in your image.  It's not unusual for conda to have these "failures" during the solve, but in the output you show, conda hasn't completed yet, so we can't say it won't succeed?

However, you seem to be on Windows? Have you seen this part of the documentation : https://pangeo-xesmf.readthedocs.io/en/latest/installation.html#notes-for-windows-users
(Problem is : ESMF, on which xESMF depends, doesn't exist for windows in the conda ecosystem)

**Comment by KashyapAnurag** [comment]
> Hi @KashyapAnurag , I'm not sure I see an error in your image.  It's not unusual for conda to have these "failures" during the solve, but in the output you show, conda hasn't completed yet, so we can't say it won't succeed?
> 
> However, you seem to be on Windows? Have you seen this part of the documentation : https://pangeo-xesmf.readthedocs.io/en/latest/installation.html#notes-for-windows-users
> (Problem is : ESMF, on which xESMF depends, doesn't exist for windows in the conda ecosystem)

Sir, i just posted the picture for the reference, it actually failed many times. So please check the issue.  Meanwhile I was trying to install xesmf for regridding, so if you can tell the alternative to it, it will be appreciable. Moreover, I am working on bias correction, so if possible please help me in this too! Thank you in advance.

**Comment by aulemahal** [comment]
I see. It just wasn't clear to me from your post and image that it completely failed, instead of just hanging (which is something conda tends to do).

The alternative to installing `xESMF` directly through conda in a normal way is, for windows users, to follow the advices in the doc. 
Otherwise an alternative to `xESMF` altogether is to use `scipy.interpolate.griddata`, but it's clearly more complex and less powerful.

As for bias correction, I would point you towards [xclim.sdba](https://xclim.readthedocs.io/en/stable/sdba.html). I'm also one of the developers of this package, so will be happy to answer issues you have on it's github.

**Comment by danielmwatkins** [comment]
I'm also having issues with installation using conda. I'm using Python 3.9.12 on MacOS 12.4. When I run conda install, I get an "UnsatisfiableError" but no explanation appears. Is xESMF incompatible with Python 3.9.12?
![image](https://user-images.githubusercontent.com/8204369/188893351-c36d0162-81f7-473b-85a9-5c461b23da38.png)

**Comment by aulemahal** [comment]
Hi @danielmwatkins , 
is there a reason for your use of a specific conda-forge label? When I look at the repo, I see that this label provides xESMF 0.3.0, which is wildly out-of-date. I'm not completely sure why it would be incompatible/unsatisfiable, but we won't be able to help you as much with an old version like this one. 
Haha, it's so old that it came out a few months _before_ python 3.9.  So, we evidently can't promise that version of xesmf would work with that python.

Even though we don't have a MacOS CI, recent versions of xESMF/esmpy/esmf should all work for MacOS (but not windows).

I would recommend installing xESMF with:
`conda install -c conda-forge xesmf==0.6.3`

**Comment by danielmwatkins** [comment]
Thanks for your reply! I should have copied and pasted the first attempt -
the output was exactly the same, this was just trying another approach
based on the conda-forge listing. I had initially tried just "conda install
-c conda-forge xesmf".

I tried the command with xesmf==0.6.3 and it failed three environment
solves, then said
"Found conflicts! Looking for incompatible packages.

This can take several minutes.  Press CTRL-C to abort.

failed



UnsatisfiableError:


"
Do you think that it's an incompatibility with the M1 chip?

**Comment by huard** [comment]
I suppose it is, see https://github.com/pangeo-data/xESMF/issues/165
