### ISSUE TITLE
Error in opening dataset from Pangeo- Intake-ESM

### ISSUE THREAD

**Issue by KashyapAnurag** [pangeo-data/xESMF#195]
In google colab, while opening the datasets of Pangeo, I am getting the error as attached below. FYI I have given the complete code:

1.    Installations and Imports
                  !pip install astropy>=3.1
                  !pip install sunpy
                  !pip install intake-esm
                  import intake 
2. Code for data: 
 
url= "https://cmip6.storage.googleapis.com/pangeo-cmip6.json"                       
col_gs = intake.open_esm_datastore(url)
query = dict(experiment_id=['ssp126',  'ssp585' ],                                
             source_id= ['CNRM-CM6-1-HR'],
             table_id='day',
             variable_id=['tasmax']
            )

col_gs_subset1 = col_gs.search(require_all_on=['source_id'], **query) 
col_gs_subset1.df
![image](https://user-images.githubusercontent.com/91251342/189830557-de90c296-442d-47ce-bab0-86172bd6742c.png)

dset_dict = col_gs_subset1.to_dataset_dict(zarr_kwargs={'consolidated': True})

![image](https://user-images.githubusercontent.com/91251342/189829405-3015bf68-d476-4e34-897e-e8e03cc5e69a.png)

Although these codes are working fine with Jupyter notebook, but In the google Colab, it is not working. 
Please help me!

**Comment by aulemahal** [comment]
I think you posted this in the wrong repo? This question looks like either a Google Colab issue or an Intake-esm one.
As far as I understand, `pip` shouldn't have installed `intake-esm` without updating "requests", so the issues revolves around this. Good luck!
