### ISSUE TITLE
Documentation is missing conservative_normed

### ISSUE THREAD

**Issue by PBrockmann** [pangeo-data/xESMF#199]
I have really appreciated the documentation.
Perhaps a small update about the different regridding algorithms.
There is finally 6 of them.
    - 'bilinear'
    - 'conservative', **need grid corner information**
    - 'conservative_normed', **need grid corner information**
    - 'patch'
    - 'nearest_s2d'
    - 'nearest_d2s'

In documentation, https://xesmf.readthedocs.io/en/latest/notebooks/Compare_algorithms.html
it is written Comparison of 5 regridding algorithms and indeed the conservative_normed is described only from from https://xesmf.readthedocs.io/en/latest/notebooks/Masking.html

**Comment by PBrockmann** [comment]
My suggestion would be to make visible the bindings between xESMF and ESMF. 

The different methods (6 and not 5).
       'bilinear': ESMF.RegridMethod.BILINEAR,
       'conservative': ESMF.RegridMethod.CONSERVE,
       'conservative_normed': ESMF.RegridMethod.CONSERVE,
       'patch': ESMF.RegridMethod.PATCH,
       'nearest_s2d': ESMF.RegridMethod.NEAREST_STOD,
       'nearest_d2s': ESMF.RegridMethod.NEAREST_DTOS,

And how conservative_normed implies normalisation type as found in the code:
   if method == 'conservative_normed':
       norm_type = ESMF.NormType.FRACAREA
   else:
       norm_type = ESMF.NormType.DSTAREA

Thks

**Comment by raphaeldussin** [comment]
Hi @PBrockmann ,

We'd be happy to take a pull request with your suggestions for documentation improvements.

Thanks for your input!

**Comment by huard** [comment]
Now fixed. Thanks for the suggestion.
