### ISSUE TITLE
JiaweiZhuang repo is confusing

### ISSUE THREAD

**Issue by aaron-kaplan** [pangeo-data/xESMF#200]
Apparently this repo (pangeo-data/xESMF) is where releases to ~PyPI and~ conda-forge are coming from now, but [JiaweiZhuang/xESMF](https://github.com/JiaweiZhuang/xESMF) doesn't say anything about the move, is still the first hit from Google when I search for "xesmf github", and still has open issues and pull requests, some opened in the past month. Likewise, https://xesmf.readthedocs.io/en/latest/ outranks https://pangeo-xesmf.readthedocs.io/en/latest/ on Google. Has the previous maintainer formally handed over ownership or not? If not, I would suggest using a different name for this fork. The status quo is confusing.

**Comment by aulemahal** [comment]
The former owner has disappeared into another dimension, or so it seems.
Are you suggesting renaming to something else than xESMF?

Could we instead simply take down the repo, pypi package and/or the RTD website? May be those organizations have some way of removing ghost content like that?

**Comment by aaron-kaplan** [comment]
I stand corrected about PyPI. I thought I had seen new releases there, but after seeing your reply I checked again and indeed it hasn't been updated since 2020. That's even worse :-(. You're actually squatting somebody else's project name on conda-forge.

If you can get github, pypi, and rtd to give you control of the old projects, that would be great. You could change the README on github to direct people here, and you could publish new releases to the existing PyPI package. Simply taking those projects down would be a bad thing, especially the PyPI one, because that would break all the existing programs that depend on it.

**Comment by raphaeldussin** [comment]
@aaron-kaplan back in 2019/2020 @JiaweiZhuang asked xesmf contributors to take on maintainers role so he can focus on his personal research projects. Unfortunately shortly after we lost contact with him and the activity on his repos seem to have stopped. We are slowly taking  ownership over pip, conda, rtd but this requires a certain time of inactivity for projects to be transferred, which seems perfectly reasonable. I don’t know about @JiaweiZhuang ’s situation at the moment.
