### ISSUE TITLE
release a `0.6.4` version for esmpy `8.4` support

### ISSUE THREAD

**Issue by raphaeldussin** [pangeo-data/xESMF#217]
since the new esmpy (with module name change) is now on conda, we should put in a new release so that conda does not install xESMF<=0.6.3 with esmpy >=8.4
@huard @aulemahal  thoughts?

**Comment by huard** [comment]
Good for me.

**Comment by htmlboss** [comment]
Well that explains why I was getting a `ESMPY` module not found import error after a fresh xESMF install through conda forge haha.

New version makes sense to me
