### ISSUE TITLE
Test against python 3.10 (3.11 ?)

### ISSUE THREAD

**Issue by aulemahal** [pangeo-data/xESMF#225]
Python 3.7 is slowly being deprecated and python 3.10 has been there for a while!  xESMF seems to often be used on machines with older python versions and by users not having all the permissions and power to update those, so we might not want to drop python 3.7 testing and support for the moment.

However, I think we should add a CI build for 3.10, and may be even for 3.11, to take some steps ahead?

**Comment by huard** [comment]
Agreed, let's do this. I suggest we use the opportunity to test different ESMF versions. A full test matrix would probably be too expensive to run, but we could do something like this: 

- 3.11 : 8.4
- 3.10: 8.3
- 3.9: 8.2
- 3.8: 8.1
- 3.7: 8.0
