### ISSUE TITLE
CI update to micromamba

### ISSUE THREAD

**Issue by raphaeldussin** [pangeo-data/xESMF#232]
our friends at https://github.com/xgcm/ have switch their CI to micromamba:

https://github.com/xgcm/xgcm/pull/577

should we follow or keep the workaround from PR #229 ?
Any pros/cons for either solution?

**Comment by huard** [comment]
@Zeitsperre Thoughts ?

**Comment by Zeitsperre** [comment]
Wow! That's quite the reduction in build time. I think we should be looking into that action + caching as well!

**Comment by raphaeldussin** [comment]
@Zeitsperre  do you want to lead the charge on this?

**Comment by Zeitsperre** [comment]
@raphaeldussin Sure! I can submit a PR for this if you'd like. Will aim for end of day today.
