### ISSUE TITLE
xESMF bugs on python 3.11

### ISSUE THREAD

**Issue by JiyongLeeGit** [pangeo-data/xESMF#265]
I am facing troubles when installing xESMF.
I followed the instruction on the website (created clean conda environment and activate it).
But, I am getting errors when I run pytest -v --pyargs xesmf as below.

=================================================================== short test summary info ====================================================================
FAILED anaconda3/envs/xesmf_env/lib/python3.11/site-packages/xesmf/tests/test_backend.py::test_regrid - esmpy.util.exceptions.PIOMissing: This function requires ESMF to have been built with PIO.
FAILED anaconda3/envs/xesmf_env/lib/python3.11/site-packages/xesmf/tests/test_backend.py::test_read_weights - esmpy.util.exceptions.PIOMissing: This function requires ESMF to have been built with PIO.
FAILED anaconda3/envs/xesmf_env/lib/python3.11/site-packages/xesmf/tests/test_frontend.py::test_to_netcdf - esmpy.util.exceptions.PIOMissing: This function requires ESMF to have been built with PIO.
FAILED anaconda3/envs/xesmf_env/lib/python3.11/site-packages/xesmf/tests/test_frontend.py::test_to_netcdf_nans - esmpy.util.exceptions.PIOMissing: This function requires ESMF to have been built with PIO.
FAILED anaconda3/envs/xesmf_env/lib/python3.11/site-packages/xesmf/tests/test_frontend.py::test_regrid_dataarray[True] - ValueError: dataset must include lon/lat or be CF-compliant
FAILED anaconda3/envs/xesmf_env/lib/python3.11/site-packages/xesmf/tests/test_frontend.py::test_regrid_dataarray_endianess[True] - AssertionError: 
FAILED anaconda3/envs/xesmf_env/lib/python3.11/site-packages/xesmf/tests/test_frontend.py::test_regrid_dataarray_endianess[False] - AssertionError: 
=================================================== 7 failed, 109 passed, 1 skipped, 301 warnings in 33.32s ====================================================

Below is my conda list
# Name                    Version                   Build  Channel
arrow-cpp                 12.0.0           hce30654_1_cpu    conda-forge
aws-c-auth                0.6.26               h0c2019c_6    conda-forge
aws-c-cal                 0.5.26               h9c01cc2_0    conda-forge
aws-c-common              0.8.17               hb547adb_0    conda-forge
aws-c-compression         0.2.16               h7a7fafa_6    conda-forge
aws-c-event-stream        0.2.20               heb79caa_6    conda-forge
aws-c-http                0.7.7                h5140e40_3    conda-forge
aws-c-io                  0.13.21              hc2875bd_4    conda-forge
aws-c-mqtt                0.8.6               h34492a6_15    conda-forge
aws-c-s3                  0.2.8                h28047f4_4    conda-forge
aws-c-sdkutils            0.1.9                h7a7fafa_1    conda-forge
aws-checksums             0.1.14               h7a7fafa_6    conda-forge
aws-crt-cpp               0.19.9               h1ca6c90_5    conda-forge
aws-sdk-cpp               1.10.57             hc8901a9_10    conda-forge
blosc                     1.21.4               hc338f07_0    conda-forge
bokeh                     3.1.1              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h1a8c8d9_8    conda-forge
brotli-bin                1.0.9                h1a8c8d9_8    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.19.1               hb547adb_0    conda-forge
ca-certificates           2023.5.7             hf0a4a13_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cf_xarray                 0.8.1              pyhd8ed1ab_0    conda-forge
cftime                    1.6.2           py311h4add359_1    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7           py311hd6ee22a_0    conda-forge
curl                      8.1.0                h912dcd9_0    conda-forge
cytoolz                   0.12.0          py311he2be06e_1    conda-forge
dask                      2023.5.0           pyhd8ed1ab_0    conda-forge
dask-core                 2023.5.0           pyhd8ed1ab_0    conda-forge
distributed               2023.5.0           pyhd8ed1ab_0    conda-forge
esmf                      8.4.2           nompi_ha1e40e6_0    conda-forge
esmpy                     8.4.2              pyhc1e730c_1    conda-forge
freetype                  2.12.1               hd633e50_1    conda-forge
fsspec                    2023.5.0           pyh1a96a4e_0    conda-forge
geos                      3.11.2               hb7217d7_0    conda-forge
gflags                    2.2.2             hc88da5d_1004    conda-forge
glog                      0.6.0                h6da1cb0_0    conda-forge
hdf4                      4.2.15               h8111dcc_6    conda-forge
hdf5                      1.14.0          nompi_h6b85c65_103    conda-forge
icu                       72.1                 he12128b_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.6.0              pyha770c72_0    conda-forge
importlib_metadata        6.6.0                hd8ed1ab_0    conda-forge
iniconfig                 2.0.0                    pypi_0    pypi
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
krb5                      1.20.1               h69eda48_0    conda-forge
lcms2                     2.15                 hd835a16_1    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libabseil                 20230125.0      cxx17_hb7217d7_1    conda-forge
libaec                    1.0.6                hb7217d7_1    conda-forge
libarrow                  12.0.0           h5d58556_1_cpu    conda-forge
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_8    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_8    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_8    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libcrc32c                 1.1.2                hbdafb3b_0    conda-forge
libcurl                   8.1.0                h912dcd9_0    conda-forge
libcxx                    16.0.4               h4653b0c_0    conda-forge
libdeflate                1.18                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libevent                  2.1.12               h5643135_0    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           12_2_0_hd922786_31    conda-forge
libgfortran5              12.2.0              h0eea778_31    conda-forge
libgoogle-cloud           2.10.0               he22f4c0_0    conda-forge
libgrpc                   1.54.2               h9dbdbd0_0    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libjpeg-turbo             2.1.5.1              h1a8c8d9_0    conda-forge
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
libllvm14                 14.0.6               hd1a9a77_2    conda-forge
libnetcdf                 4.9.2           nompi_h0a2dbf5_105    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libopenblas               0.3.21          openmp_hc731615_3    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libprotobuf               3.21.12              hb5ab8b9_0    conda-forge
libsqlite                 3.42.0               hb31c410_0    conda-forge
libssh2                   1.10.0               h7a5bd25_3    conda-forge
libthrift                 0.18.1               ha061701_1    conda-forge
libtiff                   4.5.0                h4f7d55c_6    conda-forge
libutf8proc               2.8.0                h1a8c8d9_0    conda-forge
libwebp-base              1.3.0                h1a8c8d9_0    conda-forge
libxcb                    1.15                 hf346824_0    conda-forge
libxml2                   2.11.4               he3bdae6_0    conda-forge
libzip                    1.9.2                h76ab92c_1    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
llvm-openmp               16.0.4               h1c12783_0    conda-forge
llvmlite                  0.40.0          py311hea943cd_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.3.2           py311h854b99e_0    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
markupsafe                2.1.2           py311he2be06e_0    conda-forge
msgpack-python            1.0.5           py311hd6ee22a_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
netcdf-fortran            4.6.1           nompi_h8e202b2_100    conda-forge
netcdf4                   1.6.3           nompi_py311h6706b3f_102    conda-forge
numba                     0.57.0          py311hbf3c4e2_0    conda-forge
numpy                     1.24.3          py311hb8f3215_0    conda-forge
openjpeg                  2.5.0                hbc2ba62_2    conda-forge
openssl                   3.1.0                h53f4e23_3    conda-forge
orc                       1.8.3                hef0d403_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.1           py311h9e438b8_1    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
partd                     1.4.0              pyhd8ed1ab_0    conda-forge
pillow                    9.5.0           py311h095fde6_1    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
platformdirs              3.5.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0                    pypi_0    pypi
pooch                     1.7.0              pyha770c72_3    conda-forge
psutil                    5.9.5           py311he2be06e_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
pyarrow                   12.0.0          py311h0e52918_1_cpu    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.3.1                    pypi_0    pypi
python                    3.11.3          h1456518_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py311he2be06e_5    conda-forge
re2                       2023.02.02           hb7217d7_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
scipy                     1.10.1          py311h93d07a4_3    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
shapely                   2.0.1           py311h7f8cfc4_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h17c5cce_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sparse                    0.14.0             pyhd8ed1ab_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.3.2           py311heffc1b2_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.2              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xarray                    2023.5.0           pyhd8ed1ab_0    conda-forge
xesmf                     0.7.1              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xyzservices               2023.5.0           pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h03a7124_4    conda-forge
zstd                      1.5.2                hf913c23_6    conda-forge

====================================
Any advice would be appreciated. 
Thanks for your time in advance.

**Comment by aulemahal** [comment]
Hi @JiyongLeeGit,

The first errors with  `This function requires ESMF to have been built with PIO.` are normal with a normal conda installation. These tests are testing extra functionality only available with special versions of ESMF. You can ignore them.

However, the other errors are new to me. I see that you are using python 3.11, I don't think we are testing with this version currently. Until recently, xESMF was not available on 3.11 because numba was not compatible. It seems this has changed and it introduced new bugs...  Thanks for the issue, we'll look into that!

**Comment by JiyongLeeGit** [comment]
Thanks @aulemahal for your prompt answer.
Downgrading to python 3.10 has resolved the issue.

**Comment by aulemahal** [comment]
Thanks @JiyongLeeGit , I'll reopen the issue so we can keep track of these bugs on python 3.11.

**Comment by aulemahal** [comment]
@charlesgauthier-udm

**Comment by huard** [comment]
The CI now includes 3.11 and all tests pass, at least with ESMF 8.4.

**Comment by szwang1990** [comment]
Same errors occur to my pytest:
```
========================================================================================= short test summary info ==========================================================================================
FAILED tests/test_backend.py::test_regrid - esmpy.util.exceptions.PIOMissing: This function requires ESMF to have been built with PIO.
FAILED tests/test_backend.py::test_read_weights - esmpy.util.exceptions.PIOMissing: This function requires ESMF to have been built with PIO.
FAILED tests/test_frontend.py::test_to_netcdf - esmpy.util.exceptions.PIOMissing: This function requires ESMF to have been built with PIO.
FAILED tests/test_frontend.py::test_to_netcdf_nans - esmpy.util.exceptions.PIOMissing: This function requires ESMF to have been built with PIO.
FAILED tests/test_frontend.py::test_regrid_dataarray[True] - ValueError: dataset must include lon/lat or be CF-compliant
========================================================================= 5 failed, 111 passed, 1 skipped, 300 warnings in 18.62s ==========================================================================
```
I tried both python3.11 and 3.10, but got the same errors.
Here are my **conda list**
```
# packages in environment at /home/swang/Software/anaconda3/envs/xesmf_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aws-c-auth                0.7.0                hf8751d9_2    conda-forge
aws-c-cal                 0.6.0                h93469e0_0    conda-forge
aws-c-common              0.8.23               hd590300_0    conda-forge
aws-c-compression         0.2.17               h862ab75_1    conda-forge
aws-c-event-stream        0.3.1                h9599702_1    conda-forge
aws-c-http                0.7.11               hbe98c3e_0    conda-forge
aws-c-io                  0.13.28              h3870b5a_0    conda-forge
aws-c-mqtt                0.8.14               h2e270ba_2    conda-forge
aws-c-s3                  0.3.13               heb0bb06_2    conda-forge
aws-c-sdkutils            0.1.11               h862ab75_1    conda-forge
aws-checksums             0.1.16               h862ab75_1    conda-forge
aws-crt-cpp               0.20.3               he9c0e7f_4    conda-forge
aws-sdk-cpp               1.10.57             hbc2ea52_17    conda-forge
blosc                     1.21.4               h0f2a231_0    conda-forge
bokeh                     3.2.1              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h166bdaf_9    conda-forge
brotli-bin                1.0.9                h166bdaf_9    conda-forge
brotli-python             1.0.9           py310hd8f1fbe_9    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cartopy                   0.21.1          py310h7eb24ba_1    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cf_xarray                 0.8.4              pyhd8ed1ab_0    conda-forge
cftime                    1.6.2           py310hde88566_1    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
click                     8.1.6           unix_pyh707e725_0    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0           py310hd41b1e2_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.2          py310h2372a71_0    conda-forge
dask                      2023.7.1           pyhd8ed1ab_0    conda-forge
dask-core                 2023.7.1           pyhd8ed1ab_0    conda-forge
distributed               2023.7.1           pyhd8ed1ab_0    conda-forge
esmf                      8.4.2           nompi_ha7f9e30_1    conda-forge
esmpy                     8.4.2              pyhc1e730c_1    conda-forge
exceptiongroup            1.1.2              pyhd8ed1ab_0    conda-forge
fonttools                 4.42.0          py310h2372a71_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
fsspec                    2023.6.0           pyh1a96a4e_0    conda-forge
geos                      3.11.2               hcb278e6_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
hdf4                      4.2.15               h501b40f_6    conda-forge
hdf5                      1.14.1          nompi_h4f84152_100    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4           py310hbf28c38_1    conda-forge
krb5                      1.21.1               h659d440_0    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230125.3      cxx17_h59595ed_0    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libarrow                  12.0.1           h657c46f_7_cpu    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_9    conda-forge
libbrotlidec              1.0.9                h166bdaf_9    conda-forge
libbrotlienc              1.0.9                h166bdaf_9    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.2.1                hca28451_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libgoogle-cloud           2.12.0               h840a212_1    conda-forge
libgrpc                   1.56.2               h3905398_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libnetcdf                 4.9.2           nompi_h7e745eb_109    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libnuma                   2.0.16               h0b41bf4_1    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               4.23.3               hd1fb520_0    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libthrift                 0.18.1               h8fd135c_2    conda-forge
libtiff                   4.5.1                h8b53f26_0    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxml2                   2.11.4               h0d562d8_0    conda-forge
libzip                    1.9.2                hc929e4a_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvmlite                  0.40.1          py310h1b8f574_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.3.2           py310h0cfdcf0_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
markupsafe                2.1.3           py310h2372a71_0    conda-forge
matplotlib-base           3.7.1           py310he60537e_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.1.4           py310h37cc914_0    conda-forge
mpich                     4.1.1              h846660c_100    conda-forge
msgpack-python            1.0.5           py310hdf3cbec_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
netcdf-fortran            4.6.1           nompi_hec59055_101    conda-forge
netcdf4                   1.6.4           nompi_py310h6f5dce6_101    conda-forge
numba                     0.57.1          py310h0f6aa51_0    conda-forge
numpy                     1.24.4          py310ha4c1d20_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
orc                       1.9.0                h385abfd_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3           py310h7cbd5c2_1    conda-forge
partd                     1.4.0              pyhd8ed1ab_0    conda-forge
pillow                    10.0.0          py310h582fbeb_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
platformdirs              3.10.0             pyhd8ed1ab_0    conda-forge
pluggy                    1.2.0              pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
proj                      9.2.1                ha643af7_0    conda-forge
psutil                    5.9.5           py310h1fa729e_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyarrow                   12.0.1          py310h0576679_7_cpu    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyproj                    3.6.0           py310h24ef57a_1    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.4.0              pyhd8ed1ab_0    conda-forge
python                    3.10.12         hd12c33a_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h5764c6d_5    conda-forge
re2                       2023.03.02           h8c504da_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
s2n                       1.3.46               h06160fa_0    conda-forge
scipy                     1.11.1          py310ha4c1d20_0    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
shapely                   2.0.1           py310h056c13c_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sparse                    0.14.0             pyhd8ed1ab_0    conda-forge
sqlite                    3.42.0               h2c6b66d_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.3.2           py310h2372a71_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucx                       1.14.1               h0aa22dc_2    conda-forge
unicodedata2              15.0.0          py310h5764c6d_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
wheel                     0.41.0             pyhd8ed1ab_0    conda-forge
xarray                    2023.7.0           pyhd8ed1ab_0    conda-forge
xesmf                     0.7.1              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xyzservices               2023.7.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                hfc55251_7    conda-forge
```

Thanks in advance.
