### ISSUE TITLE
There is a problem when I import xesmf

### ISSUE THREAD

**Issue by zmli-666** [pangeo-data/xESMF#273]
![QQ截图20230615211100](https://github.com/pangeo-data/xESMF/assets/74288520/0b09af90-6f0e-4a73-b4e3-c59055c86577)

**Comment by huard** [comment]
Please provide information on your Python version, how you installed xESMF, and which version of ESMF and xESMF you're installing.

**Comment by aulemahal** [comment]
Also, you might find help in #269 or #246.
