### ISSUE TITLE
installation python 3.11 xESMF

### ISSUE THREAD

**Issue by fipoucat** [pangeo-data/xESMF#278]
I installed xESMF using conda and python 3.11, when testing I noticed 4 that failed :+1: 
FAILED xesmf/tests/test_backend.py::test_regrid - esmpy.util.exceptions.PIOMissing: This function requires ESMF to have been bui...
FAILED xesmf/tests/test_backend.py::test_read_weights - esmpy.util.exceptions.PIOMissing: This function requires ESMF to have been bui...
FAILED xesmf/tests/test_frontend.py::test_to_netcdf - esmpy.util.exceptions.PIOMissing: This function requires ESMF to have been bui...
FAILED xesmf/tests/test_frontend.py::test_to_netcdf_nans - esmpy.util.exceptions.PIOMissing: This function requires ESMF to have been bui...
======= 4 failed, 113 passed, 1 sk

Any hint on what to do mainly the netcdf related?

Thank you

**Comment by huard** [comment]
Hi @fipoucat 

Sorry for the delay, did you manage to find a solution? I suspect it has to do with how esmpy was installed.
