### ISSUE TITLE
ReadTheDocs only pointing to master branch

### ISSUE THREAD

**Issue by aulemahal** [pangeo-data/xESMF#285]
A cause of issue #283 seems to be that the documentation on RTD is the one for the master branch _only_. I don't see the "stable" version, which should be default. 

I also don't have access to the RTD settings.

**Comment by huard** [comment]
Added stable to the versions. Unfortunately, the last stable release used Py3.8 and the builds fail. I suspect it's because the latest numpy does not support 3.8. 

This should be fixed with the next release.
