### ISSUE TITLE
CI fails with `sparse` > 0.14

### ISSUE THREAD

**Issue by raphaeldussin** [pangeo-data/xESMF#322]
apparently `isnan` is not part of `sparse`, we can tag to `0.14` for now but we should find a more permanent fix

**Comment by aulemahal** [comment]
It is, but there was simply some oversight when they implemented the "Array API" in 0.15. 
See https://github.com/pydata/sparse/issues/622, which was very quickly taken care of! Next minor release should fix it and we shouldn't need to pin.

**Comment by aulemahal** [comment]
Running the CI manually with sparse 0.15.1 and the problem is gone!
