### ISSUE TITLE
xESMF 0.8.2 conda-forge release failing on osx-arm64

### ISSUE THREAD

**Issue by durack1** [pangeo-data/xESMF#327]
I just went to create a new env today and hit:

```python
(base) home:home ~$ mamba create --dry-run -n xesmf -c conda-forge xesmf
Looking for: ['xesmf']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
Could not solve for environment specs
The following packages are incompatible
└─ xesmf is not installable because there are no viable options
   ├─ xesmf [0.1.2|0.2.1|0.2.2|0.3.0] would require
   │  └─ esmpy, which does not exist (perhaps a missing channel);
   └─ xesmf [0.4.0|0.5.0|...|0.6.3] would require
      └─ esmpy >=8.0.0 , which does not exist (perhaps a missing channel).
```

This surprised me as it seems [xesmf 0.8.2](https://anaconda.org/conda-forge/xesmf) is available for `noarch`, and so is [esmpy 8.4.2](https://anaconda.org/conda-forge/esmpy)

Some further diagnostic env info:

```python
(base) home:home ~$ python
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11) 
[Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
(base) home:home ~$$ mamba --version
mamba 1.5.6
conda 23.11.0
```

**Comment by aulemahal** [comment]
Indeed, this is strange. The output you showed seems to imply that xesmf >= 0.7 was not considered for the environment, why should that be ?  At 0.7 we introduced a pin on numba >= 0.55.2, but that package also exists for your architecture and python version, so I'm not sure.

I'm not an expert in how `mamba` works, but could you try "forcing" the versions we _know_ exist ? Like 
```
mamba create --dry-run -n xesmf -c conda-forge "xesmf==0.8.2" "esmpy>=0.8"
```
and see if the output gives tou more info ?

**Comment by durack1** [comment]
It turns out my issue was due to some kind of conda/mamba corruption. I just reinstalled [mambaforge from scratch](https://github.com/conda-forge/miniforge/releases) and it seems it's now working perfectly with a new env including `xesmf 0.8.2`, `esmpy 8.4.2` and `esmf 8.4.2`, so apologies for wasting your time
