### ISSUE TITLE
Upstream CI failure - xarray update

### ISSUE THREAD

**Issue by aulemahal** [pangeo-data/xESMF#338]
https://github.com/pangeo-data/xESMF/actions/runs/7880164199

Test failures triggered by some changes in xarray regarding the `xr.core.pycompat` submodule.

On the other hand, the last run was made with ESMF 8.6, and it seems like no errors were related to this long awaited upgrade!

**Comment by TomNicholas** [comment]
Wait why are you guys using xarray.core.pycompat? Anything in core is not public API, and therefore liable to change at any time...

**Comment by aulemahal** [comment]
Hmm, seems it is only used for the `is_dask_collection` method, I guess it was overlooked when implementing that code...
