### ISSUE TITLE
Replace "UV-CDAT" with "xCDAT" in "Other geospatial regridding tools" docs page  

### ISSUE THREAD

**Issue by tomvothecoder** [pangeo-data/xESMF#357]
Hi, an xCDAT user pointed out in this [issue](https://github.com/xCDAT/xcdat/issues/639) that there is an old reference to [Regridder in UV-CDAT](https://uvcdat.llnl.gov/documentation/cdms/cdms_4.html) (broken link) in the [Other geospatial regridding tools](https://xesmf.readthedocs.io/en/stable/other_tools.html) page. 

xCDAT is a modern successor to CDAT and includes a Python port of [Regrid2](https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.regrid2.Regrid2Regridder.html), which is the regridder found in CDAT/UV-CDAT.

 Thanks!

**Comment by huard** [comment]
Please adjust https://github.com/pangeo-data/xESMF/pull/358 as needed.
