### ISSUE TITLE
test against xarray main branch

### ISSUE THREAD

**Issue by dcherian** [pangeo-data/xESMF#37]
This would be good to catch things like #36 before releasing a new xarray version.

See https://github.com/xgcm/xgcm/blob/b2fc97e29c6e262f69dc699d4c31dd2ad3ee53fc/.github/workflows/ci.yaml#L86-L114 for an example wiht github workflows.

**Comment by raphaeldussin** [comment]
any volunteer for this? wink to @andersy005

**Comment by andersy005** [comment]
> any volunteer for this? wink to @andersy005

This is straightforward to do :) Expect a PR from me soon
