### ISSUE TITLE
0.8.6: int32 to int64 bug

### ISSUE THREAD

**Issue by peterdudfield** [pangeo-data/xESMF#381]
Im trying to regrid a array of `(1, 43, 12, 455, 639)` to a grid of `(704, 548)` (the last 3 dimensions get regridder).

my code is
```
regridder = xe.Regridder(ds_raw, ds_target_coords, method=method)
ds_regridded = regridder(ds_raw).compute(scheduler="single-threaded")
```

With numpy 2.0.0 this does not work as I get the error

```
 ValueError: cannot reshape array of size 112167095040 into shape (np.int32(704), np.int32(548), np.int32(639), np.int32(455)), 497945344
```
with numpy<2.0.0 and xesmf==0.8.5, it works fine

I think this is because these shapes need to be `int64` in order to be multipled together to give `112167095040`. 
Im dont know enough how this works to try and fix this, can anyone help?

Here's where the code is - https://github.com/openclimatefix/pvnet_app/blob/main/pvnet_app/data.py#L206
Here the error - https://github.com/openclimatefix/pvnet_app/actions/runs/9940657964

please let me know if you need anymore detail, and I could probably try to put a minimal bug to help if you like

**Comment by huard** [comment]
Hi @peterdudfield 

Could you check if https://github.com/pangeo-data/xESMF/pull/377 solves this ? If it does we'll merge it and make a quick release. 

Thanks,

**Comment by peterdudfield** [comment]
#377 looks like it will fix it. I wont have time to test it for a while, so dont hold back the merge becasue of me

**Comment by peterdudfield** [comment]
i mangaed to test it, yea it looks like this sorts it. If you could do a release I would appreciate it

**Comment by peterdudfield** [comment]
Sorry to re open this, do you know when 0.8.7 will be release on conda forge

This is what happens when i do `conda install -c conda-forge xesmf esmpy -y` on github actions

![Screenshot 2024-07-17 at 14 25 54](https://github.com/user-attachments/assets/9f1a0f99-5fb2-4b75-bf5d-9e8fbf372fc7)

**Comment by aulemahal** [comment]
Hi @peterdudfield . Publishing on conda-forge requires a human interaction after a bot submits a PR to the feedstock repo. Thus you can always expected some delay between the github release and the conda-forge release, this is normal.
