### ISSUE TITLE
Documenting installing latest v0.5.0 with pip is not possible currently

### ISSUE THREAD

**Issue by ahuang11** [pangeo-data/xESMF#54]
From my understanding, Jiawei still owns the pypi package which is at 0.3.0 so `pip install -U xesmf` doesn't install v0.5.0.

Maybe temporarily update the docs at https://pangeo-xesmf.readthedocs.io/en/latest/installation.html to say it will only install up to v0.3.0 for pip

**Comment by huard** [comment]
Indeed. Could you review the PR ?
