### ISSUE TITLE
Remove xarray<=0.16.0 pin (just block 0.16.1)

### ISSUE THREAD

**Issue by jthielen** [pangeo-data/xESMF#57]
Not sure if it is better to get a quick fix to this posting here or on the conda-forge feedstock, but it would be great if it were possible to change the current xarray<=0.16.0 pin to just prohibit the problematic 0.16.1 release (since the issue causing the pin, https://github.com/pangeo-data/xESMF/issues/36, was resolved in xarray 0.16.2). Right now, this pin unfortunately means that xskillscore (which requires xarray>=0.16.1) and xesmf cannot be installed together. Thanks!

xref https://github.com/Unidata/pyaos-ams-2021/pull/54

**Comment by ocefpaf** [comment]
Argh. I introduce that in https://github.com/pangeo-data/xESMF/commit/fb739ab920baa822838729d95100243e775a1c7b and forgot to update the conda-package :-(

**Comment by raphaeldussin** [comment]
@huard I've just merged a few fixes, can we release a version 0.5.1 and propagate to conda-forge to solve issue
https://github.com/conda-forge/xesmf-feedstock/pull/12

**Comment by huard** [comment]
@raphaeldussin Sounds good. Could you update CHANGES.rst with the latest PR ?

**Comment by raphaeldussin** [comment]
@huard CHANGES.rst is up to date. can I let you bump the version?

**Comment by huard** [comment]
Done: https://github.com/pangeo-data/xESMF/releases/tag/v0.5.1
