### ISSUE TITLE
Return coordinates with names and attributes consistent with ds_out?

### ISSUE THREAD

**Issue by malmans2** [pangeo-data/xESMF#58]
Looks like `xesmf` always returns objects with coordinates named `lon` and `lat` and no attributes, even when `cf_xarray` is used under the hood. 
I'm wondering whether it would make sense to return coordinates with names and attributes consistent with `ds_out` used to build the regridder.

**Comment by huard** [comment]
Agreed. Are you comfortable submitting a PR for this ?
