### ISSUE TITLE
Hardcoded bounds dimension name.

### ISSUE THREAD

**Issue by aulemahal** [pangeo-data/xESMF#72]
https://github.com/pangeo-data/xESMF/blob/0bae6dcda466d19092cf7d48115491a21ed42269/xesmf/frontend.py#L75-L76

The lines above hardcode the name of the "bounds" dimension to `'bounds'`. This is my fault, from xarray-contrib/cf-xarray#108 and #49... It seems like CF conventions have no prescribed name for that dimension, so I'm not sure if this is a problem to be fixed here or in cf_xarray?

The current code raises an error if the input dataset uses anything else, like "bnds" or "nv".

**Comment by dcherian** [comment]
Can you infer it?
``` python
bounds_dim = set(lon_bnds.dims) - set(lon.dims)
assert len(bounds_dim) == 1
bounds_dim = bounds_dim.pop()
assert ds.sizes[bounds_dim] == 2
```

**Comment by aulemahal** [comment]
Makes complete sense and should work for most cases.
But should that snippet be in cf_xarray or here? Though I'm not sure how `cf_xarray` would implement or expose it...

**Comment by dcherian** [comment]
Could add `Dataset.cf.get_bounds_dim_name("longitude")`
