### ISSUE TITLE
version 0.5.2 is not available on conda-forge

### ISSUE THREAD

**Issue by kracwarlock** [pangeo-data/xESMF#74]
I can only find up to `0.5.1` at https://anaconda.org/conda-forge/xesmf/files. Can you please upload the latest release?

**Comment by kracwarlock** [comment]
it seems that the release url is broken https://github.com/conda-forge/xesmf-feedstock/pull/13

**Comment by huard** [comment]
I think this is fixed now.

**Comment by huard** [comment]
Or at least in the process of being fixed: https://github.com/conda-forge/xesmf-feedstock/pull/13
@ocefpaf Could you confirm it's all good ?

**Comment by ocefpaf** [comment]
> @ocefpaf Could you confirm it's all good ?

LGTM! Thanks. The conda-forge bot even found the release automatically.
