### ISSUE TITLE
Enable documentation autobuild on Readthedocs

### ISSUE THREAD

**Issue by andersy005** [pangeo-data/xESMF#8]
Now that Readthedocs provides automatic build of documentation for pull requests: https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html, it would nice to enable this feature for xesmf. This would allow us to easily validate some of the PRs (for instance, #4).

Apart from @JiaweiZhuang, is there anyone in @pangeo-data/xesmf with admin access to existing xesmf repo on Readthedocs to enable this?

**Comment by raphaeldussin** [comment]
not that I know of...

**Comment by huard** [comment]
We might have to build the docs from another account until @JiaweiZhuang shares admin permissions.

**Comment by rabernat** [comment]
No, no one else has access.

**Comment by huard** [comment]
Created a new link for the docs: https://pangeo-xesmf.readthedocs.io/en/latest/index.html

Just enabled the build on PRs and added @andersy005 and @raphaeldussin as maintainers. 

@andersy005 Can we add the RTD build to the CI checks ?

**Comment by andersy005** [comment]
> @andersy005 Can we add the RTD build to the CI checks ?

I just enabled this option via RTD settings page. RTD check should starting appearing along side GitHub action CI checks on PRs.

**Comment by huard** [comment]
Nice, thanks !

**Comment by raphaeldussin** [comment]
does not seem to work on PR https://github.com/pangeo-data/xESMF/pull/22 unless I am missing something

**Comment by andersy005** [comment]
It appears that the RTD webhook wasn't properly set up on this repo. I re-synced the webhook and I am going to test it.

**Comment by andersy005** [comment]
It is working:


![Screen Shot 2020-09-04 at 5 01 01 PM](https://user-images.githubusercontent.com/13301940/92290128-3ea79600-eed0-11ea-91d9-4e99c5e18539.png)

**Comment by raphaeldussin** [comment]
closing issue since it's working now!
