### ISSUE TITLE
Test with ESMF 8.1

### ISSUE THREAD

**Issue by huard** [pangeo-data/xESMF#82]
A new release of ESMF is available. We should 
- [ ] confirm xESMF works, and 
- [ ] identify new features we want to expose.

https://github.com/esmf-org/esmf/releases/tag/ESMF_8_1_0

**Comment by Plantain** [comment]
Just from some trivial testing with our own workloads, it seems considerably slower than 8.0.1.

Could we have MOAB exposed through xESMF to try?
The integration of the MOAB mesh library, developed by the U.S. Department of Energy, into ESMF, has reached a milestone that supports application-level testing. All users of ESMF are encouraged to begin testing their applications with the MOAB option turned ON. Preliminary results indicate that MOAB provides improved performance and scaling, and reduced memory footprint. Applications seeking to go to very high resolution grids should benefit from this new capability. The MOAB mesh feature is still OFF by default in this release, but can easily be turned ON from the application level, any time during the run. The available regridding features supported by the MOAB based implementation are clearly listed in the detailed release notes.

**Comment by huard** [comment]
Is `ESMF_MeshSetMOAB()` exposed through ESMPy? 

My guess is that you'd first need to include it here: https://github.com/esmf-org/esmf/blob/develop/src/addon/ESMPy/src/ESMF/interface/cbindings.py

**Comment by rokuingh** [comment]
@huard @Plantain we have created a feature request for this under #[37](https://github.com/esmf-org/esmf-support/issues/37).

**Comment by Plantain** [comment]
Is that a private repo? I can't see it.

**Comment by rokuingh** [comment]
Oops, my mistake, it is. We are just moving our issues over to github and still have it set to private. Well, for now just know that we are aware of the issue. If you could let us know what the urgency is on this request it will help us to prioritize it for the upcoming release cycle.

**Comment by Plantain** [comment]
Well, I don't know about urgent but I think it should be a hard block on
making MOAB the default if all the users of ESMF via ESMPy have not been
able to test their workflows in advance?

**Comment by rokuingh** [comment]
agreed. we don't plan to have MOAB be the default backend to ESMF_Mesh until 8.3.0, two releases from now, about a year out at best guess. This ticket is just to add a flag to allow a user to toggle the MOAB mesh functionality.

**Comment by huard** [comment]
Thanks @rokuingh for the info and timeline. I was wondering how to submit feature requests to ESMF. 

I've opened a ticket to benchmark performance (#91).

**Comment by rokuingh** [comment]
A feature request can be submitted with an email to esmf_support@ucar.edu.

**Comment by huard** [comment]
xESMF now tested with a range of ESMF versions, see https://github.com/pangeo-data/xESMF/pull/230
