### ISSUE TITLE
Specifying grid bounds

### ISSUE THREAD

**Issue by mgrover1** [pangeo-data/xESMF#84]
It would be nice to be able to specify the grid bounds when generating a regular, global grid, or during regridding, extract the grid bounds from the dataset that is being regridded.

**Comment by huard** [comment]
@mgrover1 Could you expand on your suggestion? Does this go beyond functionality from cf-xarray ?

https://cf-xarray.readthedocs.io/en/latest/examples/introduction.html#Feature:-Cell-boundaries-and-vertices

**Comment by mgrover1** [comment]
The current functionality from cf-xarray works for rectilinear grids, but not not for curvilinear grids.

**Comment by jbusecke** [comment]
I would be very interested in having this implemented upstream in cf-xarray (which might magically solve this issue?). 
Perhaps this [issue](https://github.com/xarray-contrib/cf-xarray/issues/163) is of interest.

**Comment by huard** [comment]
Agreed, we purposefully moved that logic into cf-xarray. 

I'll close this issue, but please don't hesitate to reopen it, if after the cf-xarray implementation we need to tweak anything here.
