### ISSUE TITLE
Zenodo DOI references outdated version

### ISSUE THREAD

**Issue by jbusecke** [pangeo-data/xESMF#85]
I want to cite xESMF for a paper, but the Zenodo badge in the Readme points to an outdated version of the original repo: https://zenodo.org/record/3700105#.YHNbrC1h2wI. 

Is there a doi for the newer versions available?

**Comment by huard** [comment]
Here it is: https://zenodo.org/record/4464833#.YHSZE3WYVhE

Will update the badge. Thanks for the catch.

**Comment by huard** [comment]
Will be fixed with #88
