### ISSUE TITLE
regrid output is always float64

### ISSUE THREAD

**Issue by brews** [pangeo-data/xESMF#99]
In a current example [in docs](https://pangeo-xesmf.readthedocs.io/en/latest/notebooks/Rectilinear_grid.html#Regrid-between-rectilinear-grids)

In short:

```python
import numpy as np
import xarray as xr
import xesmf as xe

ds = xr.tutorial.open_dataset(
    "air_temperature"
)

dr = ds["air"]  # get a DataArray
dr.dtype
# dtype('float32')

dr["lat"].values, dr["lon"].values

# (array([75. , 72.5, 70. , 67.5, 65. , 62.5, 60. , 57.5, 55. , 52.5, 50. ,
#         47.5, 45. , 42.5, 40. , 37.5, 35. , 32.5, 30. , 27.5, 25. , 22.5,
#         20. , 17.5, 15. ], dtype=float32),
#  array([200. , 202.5, 205. , 207.5, 210. , 212.5, 215. , 217.5, 220. ,
#         222.5, 225. , 227.5, 230. , 232.5, 235. , 237.5, 240. , 242.5,
#         245. , 247.5, 250. , 252.5, 255. , 257.5, 260. , 262.5, 265. ,
#         267.5, 270. , 272.5, 275. , 277.5, 280. , 282.5, 285. , 287.5,
#         290. , 292.5, 295. , 297.5, 300. , 302.5, 305. , 307.5, 310. ,
#         312.5, 315. , 317.5, 320. , 322.5, 325. , 327.5, 330. ],
#        dtype=float32))

ds_out = xr.Dataset(
    {
        "lat": (["lat"], np.arange(16, 75, 1.0, dtype="float32")),
        "lon": (["lon"], np.arange(200, 330, 1.5, dtype="float32")),
    }
)

regridder = xe.Regridder(ds, ds_out, "bilinear")

dr_out = regridder(dr)
dr_out.dtype
# dtype('float64')
```

I need manually convert this output back to `float32` a la `dr_out.astype("float32")`, otherwise my files get big. Might be worth handling this in `xesmf`?

This is an issue brought up earlier in https://github.com/JiaweiZhuang/xESMF/issues/66

Thanks for your time!

**Comment by huard** [comment]
Hi @brews, 

Question: Should the weights themselves be float32, or just the regridded output ? 

Also, would you be comfortable submitting a PR for this ?

The weights are applied here: https://github.com/pangeo-data/xESMF/blob/a04300aa50c54115a95c0c82f31652db96a506e7/xesmf/smm.py#L119

So I suspect one option would be to cast `outflat_data` to the dtype of `in_data`. 

You might also need to tweak those: 
- https://github.com/pangeo-data/xESMF/blob/a04300aa50c54115a95c0c82f31652db96a506e7/xesmf/frontend.py#L507
- https://github.com/pangeo-data/xESMF/blob/a04300aa50c54115a95c0c82f31652db96a506e7/xesmf/frontend.py#L529

**Comment by brews** [comment]
Hey @huard, thanks for the direction — that's helpful. I think I can take a stab at a PR this week.

**Comment by brews** [comment]
To your other question, I don't know that it matters so much about the weights. I think it's fine to keep weights as float64 because a user might have need for that kind of precision. The trouble that I'm running into is that input data is always quietly recast into float64, regardless of input data's precision. We're also loosing attributes, etc. but this cast output is pain because the output files are considerably larger if the input is float32.

Maybe y'all want to keep everything cast to `float64`--  which is certainly your choice -- but then I think it would be nice to have something in documentation on this. I think it may also be important to respect legacy behavior?

My work around for this has been a wrap-around function with an optional `astype` argument that users can set. Then if `astype="float32"`, we do something like `return regridded_output.astype("float32")`.

**Comment by raphaeldussin** [comment]
Hi @brews and thanks for this issue! I think xesmf should respect the type of the input data. For accuracy purpose, weights should keep double precision but it would be reasonable to return the output such as `astype[input.dtype]`
